name: simple_state
description: A lightweight, efficient state management package for Flutter applications
version: 0.0.1
homepage:

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Cấu trúc file của project
#
# simple_state/
# ├── lib/
# │   ├── simple_state.dart
# │   └── src/
# │       ├── store.dart
# │       ├── consumer.dart
# │       ├── selector.dart
# │       ├── listenable.dart
# │       ├── complex_store.dart
# │       ├── provider.dart
# │       ├── utils.dart
# │       └── metrics.dart
# ├── test/
# │   └── simple_state_test.dart
# ├── example/
# │   ├── pubspec.yaml
# │   └── lib/
# │       └── main.dart
# ├── CHANGELOG.md
# ├── LICENSE
# ├── README.md
# └── pubspec.yaml